# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaPrincipal(object):
    def setupUi(self, telaPrincipal):
        telaPrincipal.setObjectName("telaPrincipal")
        telaPrincipal.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telaPrincipal.sizePolicy().hasHeightForWidth())
        telaPrincipal.setSizePolicy(sizePolicy)
        telaPrincipal.setMinimumSize(QtCore.QSize(500, 300))
        telaPrincipal.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/iconeAlerta.png.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        telaPrincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(telaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgba(102, 200, 135, 240);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TXT_INPUTCIDADE = QtWidgets.QLineEdit(self.frame)
        self.TXT_INPUTCIDADE.setObjectName("TXT_INPUTCIDADE")
        self.gridLayout_2.addWidget(self.TXT_INPUTCIDADE, 2, 0, 1, 1)
        self.BTN_VERIFICARCLIMA = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.BTN_VERIFICARCLIMA.setFont(font)
        self.BTN_VERIFICARCLIMA.setObjectName("BTN_VERIFICARCLIMA")
        self.gridLayout_2.addWidget(self.BTN_VERIFICARCLIMA, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LABEL_CIDADE = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LABEL_CIDADE.sizePolicy().hasHeightForWidth())
        self.LABEL_CIDADE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LABEL_CIDADE.setFont(font)
        self.LABEL_CIDADE.setStyleSheet("color: rgb(0, 0, 0);")
        self.LABEL_CIDADE.setObjectName("LABEL_CIDADE")
        self.gridLayout_2.addWidget(self.LABEL_CIDADE, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LABEL_RESULTADO = QtWidgets.QLabel(self.frame_3)
        self.LABEL_RESULTADO.setText("")
        self.LABEL_RESULTADO.setObjectName("LABEL_RESULTADO")
        self.gridLayout_3.addWidget(self.LABEL_RESULTADO, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3.addWidget(self.frame_4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        telaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(telaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(telaPrincipal)

    def retranslateUi(self, telaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        telaPrincipal.setWindowTitle(_translate("telaPrincipal", "Weather Alert"))
        self.BTN_VERIFICARCLIMA.setText(_translate("telaPrincipal", "Verificar Clima"))
        self.LABEL_CIDADE.setText(_translate("telaPrincipal", "Cidade:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_telaPrincipal()
    ui.setupUi(telaPrincipal)
    telaPrincipal.show()
    sys.exit(app.exec_())
